### ISSUE TITLE
Use `windows.onload`

### ISSUE THREAD

**Issue by vidstige** [vidstige/tsdf_raytracer#1]
Today, in the entry point is named in the [html file](public/index.html#L5) as `start_here`, instead the js-code could just say `window.onload = start_here`.

1. Remove the `onload = start_here()` from the html file
2. Change the `window.start_here = ....` to `window.onload = ...`.

**Comment by griffind2009** [comment]
I can take this.  Is it just the html file?

**Comment by vidstige** [comment]
Great! It's both the html file and the [js file](https://github.com/vidstige/tsdf_raytracer/blob/master/lib/js/raytracer.js).

**Comment by vidstige** [comment]
It seems @Diongatea beat you to it. :-/ If your interested in raytracing, perhaps you want to do something else cool?

**Comment by griffind2009** [comment]
Sure. Do you have anything else?

**Comment by vidstige** [comment]
Sure, what are you interested in? So you like 3D-rendering and such? This whole repo is a bit crude.
